// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvw0AUjf-LXcrWFvhBiYBvaQ2-wC6fQEk',
    appId: '1:139239443567:web:37f3d1d287ec068ff6d19a',
    messagingSenderId: '139239443567',
    projectId: 'intercep-production',
    authDomain: 'intercep-production.firebaseapp.com',
    storageBucket: 'intercep-production.appspot.com',
    measurementId: 'G-GY9VB5TGX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKoZZxN3DWbOQaqLT4OYGVzWota47iOBw',
    appId: '1:139239443567:android:3f9512688890a4a7f6d19a',
    messagingSenderId: '139239443567',
    projectId: 'intercep-production',
    storageBucket: 'intercep-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmBR3wt1JnlUngbwLVBkJr1L8f2SG11qo',
    appId: '1:139239443567:ios:27467655dbd8bfbaf6d19a',
    messagingSenderId: '139239443567',
    projectId: 'intercep-production',
    storageBucket: 'intercep-production.appspot.com',
    iosClientId: '139239443567-3pru3786f2uojlo3mmen4ai7gmglr5up.apps.googleusercontent.com',
    iosBundleId: 'mad.tf.fau.de.HBPerformanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmBR3wt1JnlUngbwLVBkJr1L8f2SG11qo',
    appId: '1:139239443567:ios:eabdd1aede51ccdaf6d19a',
    messagingSenderId: '139239443567',
    projectId: 'intercep-production',
    storageBucket: 'intercep-production.appspot.com',
    iosClientId: '139239443567-7fajq1j3c497ejtvrlenppgs5difep6t.apps.googleusercontent.com',
    iosBundleId: 'mad.tf.fau.de.handballPerformanceTracker',
  );
}
