// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV7n7FmKrrNeLLiJ02nXGs8pIMLtjzHFs',
    appId: '1:974814103289:web:851ef360793cebd006c428',
    messagingSenderId: '974814103289',
    projectId: 'handball-tracker-dev',
    authDomain: 'handball-tracker-dev.firebaseapp.com',
    storageBucket: 'handball-tracker-dev.appspot.com',
    measurementId: 'G-0BMS52683E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgjjjDLuQoL5CTGvlAVizQiqFfqdsXMow',
    appId: '1:974814103289:android:7044af92503d46c606c428',
    messagingSenderId: '974814103289',
    projectId: 'handball-tracker-dev',
    storageBucket: 'handball-tracker-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIopT3JQCid-K1_Ylcmc6Q7tfSVckVjLM',
    appId: '1:974814103289:ios:3b8f55c5a58d414306c428',
    messagingSenderId: '974814103289',
    projectId: 'handball-tracker-dev',
    storageBucket: 'handball-tracker-dev.appspot.com',
    iosClientId: '974814103289-aatra0lucgs28illj3v3ln7fr0phhhot.apps.googleusercontent.com',
    iosBundleId: 'mad.tf.fau.de.HBPerformanceTracker',
  );
}
